name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJson(github.event) }}' | jq
        shell: bash

      - name: Create comment
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const commentBody = `This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment`;

            github.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

            github.issues.createReaction({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: '+1'
            });

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
              http://github.com/ezzat223/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              -f body="Comment but from the API call not action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
